FROM openjdk:8
MAINTAINER gauravsharma.mvp@gmail.com
ADD ./Users/gauravsharma/IdeaProjects/BP-IAM/target/BP-IAM.jar ./Users/gauravsharma/IdeaProjects/BP-IAM/BP-IAM.jar
EXPOSE 8085
CMD ["java", "-jar", "BP-IAM.jar"]